Filename F1"C:\Users\shanm\OneDrive\Desktop\Initial_Study_Project3.txt";
Data Initial;
Infile F1 dlm = '09'x dsd missover;
Input PatientID Age State$ Length_of_Stay Total_Charge;
run;
Proc Sort Data = Initial;
by PatientID;
run;
Filename F2 "C:\Users\shanm\OneDrive\Desktop\Second_Study_Project3.txt";
Data Second;
Infile F2 dlm = '09'x dsd missover;
Input PatientID Site $ Group $ Test_Score;
Run;
Proc sort Data = Second;
by PatientID;
Run;
Data Merged;
Merge Initial Second;
by PatientID;
Run;
Proc print Data = Merged;
Title "Merged Dataset";
Run;
Proc surveyselect Data=Merged Method=SRS Sampsize=1000 Out=Sampled_Data;
run;
Proc print Data = Sampled_Data;
Title "Sampled Dataset";
run;
Proc means Data = Sampled_Data n mean std min max;
var Test_Score;
class Group;
run;
Proc freq Data = Sampled_Data;
tables Site*Group / norow nocol nopercent;
run;
Proc univariate Data = Sampled_Data normal;
var Test_Score;
run;
Data Analysis_Data;
set Sampled_Data;
if group ne "n/a" and Test_Score ne .;
run;
Proc Anova Data = Analysis_Data;
class group;
model test_score = group;
means group / tukey;
run;
Proc glm Data = Analysis_Data;
class group;
model Test_Score = group;
means group / hovtest=levene;
run;
Proc glm Data = Analysis_Data;
class group Site;
model Test_Score = group Site group*Site;
means group;
run;
Proc sgplot Data = Analysis_Data;
histogram Test_Score / group=Group transparency=0.5;
density Test_Score;
title "Histogram of Test Scores";
run;
